### PR TITLE
Fix issue with types with '...on' in their names, like 'transaction'

### PR DESCRIPTION
**Pull request by bkniffler**
Not too sure if making 'on_' to '_on_' is the right thing to do though.

### CODE REVIEW

**Comment by sladg** [comment]
@helios1138 hi, can you please review/merge this?

**Comment by sladg** [comment]
Fixes incorrect fragmentation for example in this case:
`                    person_profile: {
                        selected_programmes: 1,
                        id: 1,
                    },
`

Because of the `on_`.

It might be wise to use regex for matching instead and check for `on_` only at the start of string

**Comment by helios1138** [comment]
@sladg I see the problem now. This PR however currently does not seem to be fixing it correctly and missing tests. I will push a fix soon.

**Comment by sladg** [comment]
> @sladg I see the problem now. This PR however currently does not seem to be fixing it correctly and missing tests. I will push a fix soon.

thx! appreciate it

**Comment by helios1138** [comment]
@sladg fixed with https://github.com/helios1138/graphql-typed-client/commit/b8d467dc4e1ad577678946a7ce18833f5642e2ce

**Comment by sladg** [comment]
> @sladg fixed with [b8d467d](https://github.com/helios1138/graphql-typed-client/commit/b8d467dc4e1ad577678946a7ce18833f5642e2ce)

Thx a much!

**Pull request closed without merging**
